// Massive database of common command typos

pub fn get_common_fixes() -> Vec<(&'static str, (&'static str, &'static str))> {
  vec![
    // ==================== NPM ====================
    ("npm onstall", ("npm install", "npm typo")),
    ("npm isntall", ("npm install", "npm typo")),
    ("npm intall", ("npm install", "npm typo")),
    ("npm instal", ("npm install", "npm typo")),
    ("npm instlal", ("npm install", "npm typo")),
    ("npm insatll", ("npm install", "npm typo")),
    ("npm nistall", ("npm install", "npm typo")),
    ("npm unistall", ("npm uninstall", "npm typo")),
    ("npm unintsall", ("npm uninstall", "npm typo")),
    ("npm upate", ("npm update", "npm typo")),
    ("npm udpate", ("npm update", "npm typo")),
    ("npm statr", ("npm start", "npm typo")),
    ("npm strat", ("npm start", "npm typo")),
    ("npm satrt", ("npm start", "npm typo")),
    ("npm tets", ("npm test", "npm typo")),
    ("npm tset", ("npm test", "npm typo")),
    ("npm rnu", ("npm run", "npm typo")),
    ("npm biuld", ("npm build", "npm typo")),
    ("npm bulid", ("npm build", "npm typo")),
    ("npm inint", ("npm init", "npm typo")),
    ("npm pubilsh", ("npm publish", "npm typo")),
    ("npm publsih", ("npm publish", "npm typo")),
    ("npm serach", ("npm search", "npm typo")),
    ("npm searhc", ("npm search", "npm typo")),
    ("onstall", ("install", "npm shorthand")),
    ("isntall", ("install", "npm shorthand")),
    ("intall", ("install", "npm shorthand")),
    // ==================== YARN ====================
    ("yarn isntall", ("yarn install", "yarn typo")),
    ("yarn intall", ("yarn install", "yarn typo")),
    ("yarn onstall", ("yarn install", "yarn typo")),
    ("yarn statr", ("yarn start", "yarn typo")),
    ("yarn tset", ("yarn test", "yarn typo")),
    ("yarn biuld", ("yarn build", "yarn typo")),
    ("yarn bulid", ("yarn build", "yarn typo")),
    // ==================== PNPM ====================
    ("pnpm isntall", ("pnpm install", "pnpm typo")),
    ("pnpm intall", ("pnpm install", "pnpm typo")),
    ("pnpm statr", ("pnpm start", "pnpm typo")),
    // ==================== GIT ====================
    ("git comit", ("git commit", "git typo")),
    ("git commti", ("git commit", "git typo")),
    ("git commmit", ("git commit", "git typo")),
    ("git commit", ("git commit", "git typo")),
    ("git comimt", ("git commit", "git typo")),
    ("git pussh", ("git push", "git typo")),
    ("git puhs", ("git push", "git typo")),
    ("git psuh", ("git push", "git typo")),
    ("git pus", ("git push", "git typo")),
    ("git statsu", ("git status", "git typo")),
    ("git stauts", ("git status", "git typo")),
    ("git status", ("git status", "git typo")),
    ("git sttaus", ("git status", "git typo")),
    ("git staus", ("git status", "git typo")),
    ("git checkotu", ("git checkout", "git typo")),
    ("git checout", ("git checkout", "git typo")),
    ("git chekout", ("git checkout", "git typo")),
    ("git chekcout", ("git checkout", "git typo")),
    ("git branh", ("git branch", "git typo")),
    ("git branhc", ("git branch", "git typo")),
    ("git branc", ("git branch", "git typo")),
    ("git brnach", ("git branch", "git typo")),
    ("git meger", ("git merge", "git typo")),
    ("git megre", ("git merge", "git typo")),
    ("git mrege", ("git merge", "git typo")),
    ("git pull", ("git pull", "git typo")),
    ("git plul", ("git pull", "git typo")),
    ("git puull", ("git pull", "git typo")),
    ("git clon", ("git clone", "git typo")),
    ("git clone", ("git clone", "git typo")),
    ("git cloen", ("git clone", "git typo")),
    ("git fetc", ("git fetch", "git typo")),
    ("git fethc", ("git fetch", "git typo")),
    ("git ad", ("git add", "git typo")),
    ("git add", ("git add", "git typo")),
    ("git dif", ("git diff", "git typo")),
    ("git diff", ("git diff", "git typo")),
    ("git dfif", ("git diff", "git typo")),
    ("git log", ("git log", "git typo")),
    ("git lgo", ("git log", "git typo")),
    ("git inti", ("git init", "git typo")),
    ("git initt", ("git init", "git typo")),
    ("git reset", ("git reset", "git typo")),
    ("git rset", ("git reset", "git typo")),
    ("git reabse", ("git rebase", "git typo")),
    ("git rebsae", ("git rebase", "git typo")),
    ("git stsh", ("git stash", "git typo")),
    ("git satsh", ("git stash", "git typo")),
    ("git rmeote", ("git remote", "git typo")),
    ("git remtoe", ("git remote", "git typo")),
    ("git tag", ("git tag", "git typo")),
    ("git tga", ("git tag", "git typo")),
    ("git shwo", ("git show", "git typo")),
    ("git sohw", ("git show", "git typo")),
    ("git blame", ("git blame", "git typo")),
    ("git balme", ("git blame", "git typo")),
    // ==================== CARGO ====================
    ("cargo biuld", ("cargo build", "cargo typo")),
    ("cargo bulid", ("cargo build", "cargo typo")),
    ("cargo buld", ("cargo build", "cargo typo")),
    ("cargo buidl", ("cargo build", "cargo typo")),
    ("cargo rnu", ("cargo run", "cargo typo")),
    ("cargo rnu", ("cargo run", "cargo typo")),
    ("cargo tset", ("cargo test", "cargo typo")),
    ("cargo tets", ("cargo test", "cargo typo")),
    ("cargo chekc", ("cargo check", "cargo typo")),
    ("cargo check", ("cargo check", "cargo typo")),
    ("cargo cehck", ("cargo check", "cargo typo")),
    ("cargo clen", ("cargo clean", "cargo typo")),
    ("cargo claen", ("cargo clean", "cargo typo")),
    ("cargo doc", ("cargo doc", "cargo typo")),
    ("cargo dco", ("cargo doc", "cargo typo")),
    ("cargo fmt", ("cargo fmt", "cargo typo")),
    ("cargo fmtt", ("cargo fmt", "cargo typo")),
    ("cargo cilppy", ("cargo clippy", "cargo typo")),
    ("cargo clppy", ("cargo clippy", "cargo typo")),
    ("cargo clipy", ("cargo clippy", "cargo typo")),
    ("cargo pubilsh", ("cargo publish", "cargo typo")),
    ("cargo publsih", ("cargo publish", "cargo typo")),
    ("cargo serach", ("cargo search", "cargo typo")),
    ("cargo searhc", ("cargo search", "cargo typo")),
    ("cargo benchmakr", ("cargo bench", "cargo typo")),
    ("cargo updaet", ("cargo update", "cargo typo")),
    ("cargo udpate", ("cargo update", "cargo typo")),
    // ==================== DOCKER ====================
    ("dokcer", ("docker", "docker typo")),
    ("doker", ("docker", "docker typo")),
    ("dockre", ("docker", "docker typo")),
    ("docker rnu", ("docker run", "docker typo")),
    ("docker biuld", ("docker build", "docker typo")),
    ("docker bulid", ("docker build", "docker typo")),
    ("docker pull", ("docker pull", "docker typo")),
    ("docker plul", ("docker pull", "docker typo")),
    ("docker pussh", ("docker push", "docker typo")),
    ("docker psuh", ("docker push", "docker typo")),
    ("docker ps", ("docker ps", "docker typo")),
    ("docker sp", ("docker ps", "docker typo")),
    ("docker imgaes", ("docker images", "docker typo")),
    ("docker iamges", ("docker images", "docker typo")),
    ("docker imaegs", ("docker images", "docker typo")),
    ("docker stopp", ("docker stop", "docker typo")),
    ("docker statr", ("docker start", "docker typo")),
    ("docker strat", ("docker start", "docker typo")),
    ("docker exec", ("docker exec", "docker typo")),
    ("docker exce", ("docker exec", "docker typo")),
    ("docker logs", ("docker logs", "docker typo")),
    ("docker lgo", ("docker logs", "docker typo")),
    ("docker-compose", ("docker-compose", "docker typo")),
    ("docker-compoes", ("docker-compose", "docker typo")),
    ("docker-compsoe", ("docker-compose", "docker typo")),
    // ==================== KUBERNETES ====================
    ("kubeclt", ("kubectl", "k8s typo")),
    ("kubectll", ("kubectl", "k8s typo")),
    ("kuberctl", ("kubectl", "k8s typo")),
    ("kubectl get", ("kubectl get", "k8s typo")),
    ("kubectl gt", ("kubectl get", "k8s typo")),
    ("kubectl aplply", ("kubectl apply", "k8s typo")),
    ("kubectl aply", ("kubectl apply", "k8s typo")),
    ("kubectl delte", ("kubectl delete", "k8s typo")),
    ("kubectl deelete", ("kubectl delete", "k8s typo")),
    ("kubectl desribe", ("kubectl describe", "k8s typo")),
    ("kubectl descirbe", ("kubectl describe", "k8s typo")),
    ("kubectl logs", ("kubectl logs", "k8s typo")),
    ("kubectl lgo", ("kubectl logs", "k8s typo")),
    ("kubectl exec", ("kubectl exec", "k8s typo")),
    ("kubectl exce", ("kubectl exec", "k8s typo")),
    // ==================== PYTHON ====================
    ("pyhton", ("python", "python typo")),
    ("pytohn", ("python", "python typo")),
    ("ptyhon", ("python", "python typo")),
    ("pyton", ("python", "python typo")),
    ("pyhton3", ("python3", "python typo")),
    ("pytohn3", ("python3", "python typo")),
    ("python3", ("python3", "python typo")),
    ("pip isntall", ("pip install", "pip typo")),
    ("pip intall", ("pip install", "pip typo")),
    ("pip onstall", ("pip install", "pip typo")),
    ("pip instal", ("pip install", "pip typo")),
    ("pip unintsall", ("pip uninstall", "pip typo")),
    ("pip unistall", ("pip uninstall", "pip typo")),
    ("pip freez", ("pip freeze", "pip typo")),
    ("pip freeez", ("pip freeze", "pip typo")),
    ("pip lsit", ("pip list", "pip typo")),
    ("pip serach", ("pip search", "pip typo")),
    ("pip searhc", ("pip search", "pip typo")),
    // ==================== LINUX/UNIX COMMANDS ====================
    ("sl", ("ls", "classic typo")),
    ("lss", ("ls", "ls typo")),
    ("lls", ("ls", "ls typo")),
    ("cd..", ("cd ..", "missing space")),
    ("cd.", ("cd .", "missing space")),
    ("cd-", ("cd -", "missing space")),
    ("cd~", ("cd ~", "missing space")),
    ("grpe", ("grep", "grep typo")),
    ("gerp", ("grep", "grep typo")),
    ("grp", ("grep", "grep typo")),
    ("gti", ("git", "common typo")),
    ("got", ("git", "common typo")),
    ("claer", ("clear", "clear typo")),
    ("cler", ("clear", "clear typo")),
    ("clare", ("clear", "clear typo")),
    ("clera", ("clear", "clear typo")),
    ("exti", ("exit", "exit typo")),
    ("eixt", ("exit", "exit typo")),
    ("exitt", ("exit", "exit typo")),
    ("hotp", ("htop", "htop typo")),
    ("hotp", ("htop", "htop typo")),
    ("tpo", ("top", "top typo")),
    ("sduo", ("sudo", "sudo typo")),
    ("suod", ("sudo", "sudo typo")),
    ("sudp", ("sudo", "sudo typo")),
    ("mkdri", ("mkdir", "mkdir typo")),
    ("mkidr", ("mkdir", "mkdir typo")),
    ("mkdr", ("mkdir", "mkdir typo")),
    ("rmdir", ("rmdir", "rmdir typo")),
    ("rmdri", ("rmdir", "rmdir typo")),
    ("tuch", ("touch", "touch typo")),
    ("touhc", ("touch", "touch typo")),
    ("cat", ("cat", "cat typo")),
    ("cta", ("cat", "cat typo")),
    ("catt", ("cat", "cat typo")),
    ("ehco", ("echo", "echo typo")),
    ("ecoh", ("echo", "echo typo")),
    ("echp", ("echo", "echo typo")),
    ("mv", ("mv", "mv typo")),
    ("vm", ("mv", "mv typo")),
    ("mvv", ("mv", "mv typo")),
    ("cp", ("cp", "cp typo")),
    ("pc", ("cp", "cp typo")),
    ("cpp", ("cp", "cp typo")),
    ("rm", ("rm", "rm typo")),
    ("mr", ("rm", "rm typo")),
    ("rmm", ("rm", "rm typo")),
    ("chmdo", ("chmod", "chmod typo")),
    ("chmd", ("chmod", "chmod typo")),
    ("chomd", ("chmod", "chmod typo")),
    ("chonw", ("chown", "chown typo")),
    ("chwon", ("chown", "chown typo")),
    ("chonw", ("chown", "chown typo")),
    ("pwd", ("pwd", "pwd typo")),
    ("pwdd", ("pwd", "pwd typo")),
    ("pdw", ("pwd", "pwd typo")),
    ("tial", ("tail", "tail typo")),
    ("taill", ("tail", "tail typo")),
    ("head", ("head", "head typo")),
    ("haed", ("head", "head typo")),
    ("headd", ("head", "head typo")),
    ("wegt", ("wget", "wget typo")),
    ("wgte", ("wget", "wget typo")),
    ("wetg", ("wget", "wget typo")),
    ("curl", ("curl", "curl typo")),
    ("culr", ("curl", "curl typo")),
    ("crlu", ("curl", "curl typo")),
    ("curlll", ("curl", "curl typo")),
    ("vin", ("vim", "vim typo")),
    ("vmi", ("vim", "vim typo")),
    ("vmm", ("vim", "vim typo")),
    ("nano", ("nano", "nano typo")),
    ("nao", ("nano", "nano typo")),
    ("naon", ("nano", "nano typo")),
    ("fdin", ("find", "find typo")),
    ("fnid", ("find", "find typo")),
    ("fidn", ("find", "find typo")),
    ("ssh", ("ssh", "ssh typo")),
    ("shh", ("ssh", "ssh typo")),
    ("shs", ("ssh", "ssh typo")),
    ("scp", ("scp", "scp typo")),
    ("scpp", ("scp", "scp typo")),
    ("pign", ("ping", "ping typo")),
    ("pnig", ("ping", "ping typo")),
    ("pingg", ("ping", "ping typo")),
    ("tracertoue", ("traceroute", "traceroute typo")),
    ("tracroute", ("traceroute", "traceroute typo")),
    ("netstat", ("netstat", "netstat typo")),
    ("nestat", ("netstat", "netstat typo")),
    ("netsta", ("netstat", "netstat typo")),
    ("systemclt", ("systemctl", "systemctl typo")),
    ("systemtcl", ("systemctl", "systemctl typo")),
    ("systmectl", ("systemctl", "systemctl typo")),
    ("servcie", ("service", "service typo")),
    ("serivce", ("service", "service typo")),
    ("srevice", ("service", "service typo")),
    ("reboot", ("reboot", "reboot typo")),
    ("reboto", ("reboot", "reboot typo")),
    ("reobot", ("reboot", "reboot typo")),
    ("shutdwon", ("shutdown", "shutdown typo")),
    ("shutdonw", ("shutdown", "shutdown typo")),
    ("shudown", ("shutdown", "shutdown typo")),
    // ==================== MAKE/BUILD ====================
    ("make", ("make", "make typo")),
    ("mak", ("make", "make typo")),
    ("mkae", ("make", "make typo")),
    ("amke", ("make", "make typo")),
    ("make biuld", ("make build", "make typo")),
    ("make clen", ("make clean", "make typo")),
    ("make isntall", ("make install", "make typo")),
    ("make tset", ("make test", "make typo")),
    ("cmake", ("cmake", "cmake typo")),
    ("cmkae", ("cmake", "cmake typo")),
    ("camke", ("cmake", "cmake typo")),
    // ==================== TERRAFORM ====================
    ("terraform", ("terraform", "tf typo")),
    ("terrafomr", ("terraform", "tf typo")),
    ("terrafrom", ("terraform", "tf typo")),
    ("teraform", ("terraform", "tf typo")),
    ("terraform inint", ("terraform init", "tf typo")),
    ("terraform inti", ("terraform init", "tf typo")),
    ("terraform paln", ("terraform plan", "tf typo")),
    ("terraform plna", ("terraform plan", "tf typo")),
    ("terraform aplply", ("terraform apply", "tf typo")),
    ("terraform aply", ("terraform apply", "tf typo")),
    ("terraform destory", ("terraform destroy", "tf typo")),
    ("terraform desrtoy", ("terraform destroy", "tf typo")),
    // ==================== AWS CLI ====================
    ("aws s3", ("aws s3", "aws typo")),
    ("aws 3s", ("aws s3", "aws typo")),
    ("aws ec2", ("aws ec2", "aws typo")),
    ("aws 2ec", ("aws ec2", "aws typo")),
    ("aws lambda", ("aws lambda", "aws typo")),
    ("aws lamda", ("aws lambda", "aws typo")),
    ("aws labmda", ("aws lambda", "aws typo")),
    // ==================== MISC DEV TOOLS ====================
    ("rustc", ("rustc", "rustc typo")),
    ("rsutc", ("rustc", "rustc typo")),
    ("rustup", ("rustup", "rustup typo")),
    ("rsutup", ("rustup", "rustup typo")),
    ("rustpu", ("rustup", "rustup typo")),
    ("nvm", ("nvm", "nvm typo")),
    ("nmv", ("nvm", "nvm typo")),
    ("nvmm", ("nvm", "nvm typo")),
    ("nodemon", ("nodemon", "nodemon typo")),
    ("nodeomn", ("nodemon", "nodemon typo")),
    ("nodemno", ("nodemon", "nodemon typo")),
    ("tsc", ("tsc", "tsc typo")),
    ("tscc", ("tsc", "tsc typo")),
    ("tsx", ("tsx", "tsx typo")),
    ("tsxx", ("tsx", "tsx typo")),
    ("ng", ("ng", "angular typo")),
    ("ngg", ("ng", "angular typo")),
    ("nuxt", ("nuxt", "nuxt typo")),
    ("nxut", ("nuxt", "nuxt typo")),
    ("vite", ("vite", "vite typo")),
    ("vtie", ("vite", "vite typo")),
    ("viite", ("vite", "vite typo")),
  ]
}

pub fn get_common_commands() -> Vec<&'static str> {
  vec![
    // Package managers
    "npm",
    "yarn",
    "pnpm",
    "pip",
    "cargo",
    "apt",
    "apt-get",
    "yum",
    "dnf",
    "brew",
    "chocolatey",
    "pacman",
    "gem",
    "composer",
    "maven",
    "gradle",
    // Version control
    "git",
    "svn",
    "hg",
    "mercurial",
    // Build tools
    "make",
    "cmake",
    "ninja",
    "meson",
    "gradle",
    "maven",
    "ant",
    // File operations
    "ls",
    "cd",
    "cp",
    "mv",
    "rm",
    "mkdir",
    "rmdir",
    "touch",
    "cat",
    "grep",
    "find",
    "locate",
    "which",
    "whereis",
    "ln",
    "readlink",
    "basename",
    "dirname",
    // System
    "sudo",
    "chmod",
    "chown",
    "ps",
    "kill",
    "killall",
    "top",
    "htop",
    "free",
    "df",
    "du",
    "mount",
    "umount",
    "systemctl",
    "service",
    "reboot",
    "shutdown",
    // Network
    "curl",
    "wget",
    "ping",
    "ssh",
    "scp",
    "sftp",
    "rsync",
    "netstat",
    "ifconfig",
    "ip",
    "traceroute",
    "nslookup",
    "dig",
    "nc",
    "telnet",
    // Development
    "node",
    "python",
    "python3",
    "ruby",
    "php",
    "java",
    "javac",
    "rustc",
    "gcc",
    "clang",
    "g++",
    "go",
    "perl",
    "lua",
    // Container/VM
    "docker",
    "docker-compose",
    "kubectl",
    "podman",
    "vagrant",
    "virtualbox",
    // Text editors
    "vim",
    "vi",
    "nano",
    "emacs",
    "code",
    "subl",
    // Shell utilities
    "echo",
    "printf",
    "head",
    "tail",
    "less",
    "more",
    "wc",
    "sort",
    "uniq",
    "cut",
    "paste",
    "sed",
    "awk",
    "tee",
    "xargs",
    // Compression
    "tar",
    "gzip",
    "gunzip",
    "zip",
    "unzip",
    "7z",
    "bzip2",
    // Cloud CLI
    "aws",
    "gcloud",
    "az",
    "terraform",
    "ansible",
    "kubectl",
    "helm",
  ]
}
